apiVersion: v2
name: scale-sentry
description: Kubernetes controller and validation engine for HPA scaling and traffic resilience
type: application
version: 0.3.1
appVersion: "0.3.1"
home: https://github.com/ethan-kane-ops/scale-sentry
sources:
  - https://github.com/ethan-kane-ops/scale-sentry
keywords:
  - kubernetes
  - operator
  - hpa
  - autoscaling
  - validation
  - chaos
  - resilience
maintainers:
  - name: ethan-kane-ops
    url: https://github.com/ethan-kane-ops
annotations:
  artifacthub.io/operator: "true"
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: source
      url: https://github.com/ethan-kane-ops/scale-sentry
    - name: documentation
      url: https://ethan-kane-ops.github.io/scale-sentry/
