{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "scale-sentry.fullname" . }}-manager
  labels:
    {{- include "scale-sentry.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "scale-sentry.fullname" . }}-manager
subjects:
- kind: ServiceAccount
  name: {{ include "scale-sentry.controllerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
