apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scale-sentry.fullname" . }}-controller
  labels:
    {{- include "scale-sentry.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      {{- include "scale-sentry.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        {{- include "scale-sentry.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: {{ include "scale-sentry.controllerServiceAccountName" . }}
      {{- if and (gt (int .Values.controller.replicaCount) 1) .Values.controller.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range .Values.controller.topologySpreadConstraints }}
        - maxSkew: {{ .maxSkew }}
          topologyKey: {{ .topologyKey }}
          whenUnsatisfiable: {{ .whenUnsatisfiable }}
          labelSelector:
            matchLabels:
              {{- include "scale-sentry.selectorLabels" $ | nindent 14 }}
              app.kubernetes.io/component: controller
        {{- end }}
      {{- end }}
      containers:
      - name: controller
        image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
        args:
        - controller
        - --loadgen-image={{ .Values.loadgenImage | default (printf "ghcr.io/ethan-kane-ops/scale-sentry-loadgen:%s" .Chart.AppVersion) }}
        - --observer-image={{ .Values.observerImage | default (printf "ghcr.io/ethan-kane-ops/scale-sentry-observer:%s" .Chart.AppVersion) }}
        - --observer-service-account={{ .Values.observerServiceAccount }}
        - --leader-elect={{ .Values.controller.leaderElect }}
        {{- if .Values.controller.devLogging }}
        - --dev-logging
        {{- end }}
        ports:
        - name: metrics
          containerPort: 8080
        - name: probe
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /readyz
            port: probe
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: probe
          initialDelaySeconds: 15
        resources:
          {{- toYaml .Values.controller.resources | nindent 10 }}
